version: '3.5'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  publisher_custom:
    build: .
    command: "python3 publisher.py"
    container_name: publisher
    depends_on:
      - mosquitto
    network_mode: host

  subscriber_custom:
    build:
      context: .
      dockerfile: subscriber.Dockerfile
    command: "python3 subscriber.py"
    container_name: subscriber
    depends_on:
      - mosquitto
      - publisher
    network_mode: host